# Generated by Django 4.2.2 on 2023-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, upload_to='sale'),
        ),
    ]
