# Generated by Django 4.2.2 on 2023-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sale_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
