# Generated by Django 4.2.2 on 2023-12-02 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
