# Generated by Django 4.2.2 on 2023-12-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_bike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
    ]
